import { db } from "@/lib/db";
import { NotificationService } from "./notification.service";

export class WorkflowEngine {
  /**
   * Triggers a workflow event. E.g. trigger("CAMPAIGN_STATUS", { campaignId: "123", status: "ACTIVE" })
   */
  static async trigger(triggerType: string, payload: any) {
    console.log(`[WorkflowEngine] Triggered: ${triggerType}`, payload);
    
    // Find all active workflows matching this triggerType
    const workflows = await db.workflow.findMany({
      where: {
        isActive: true,
        triggerType,
      },
      include: {
        steps: {
          orderBy: { order: "asc" }
        }
      }
    });

    for (const workflow of workflows) {
      // Evaluate if the triggerData matches the payload
      if (workflow.triggerData && typeof workflow.triggerData === "object") {
        const rules = workflow.triggerData as Record<string, any>;
        let isMatch = true;
        for (const [key, value] of Object.entries(rules)) {
          if (payload[key] !== value) {
            isMatch = false;
            break;
          }
        }
        if (!isMatch) continue; // Skip if conditions not met
      }

      // Match found, execute workflow asynchronously so it doesn't block
      this.executeWorkflow(workflow, payload).catch(e => {
        console.error(`[WorkflowEngine] Failed to execute workflow ${workflow.id}`, e);
      });
    }
  }

  static async executeWorkflow(workflow: any, payload: any) {
    const execution = await db.workflowExecution.create({
      data: {
        workflowId: workflow.id,
        status: "RUNNING",
        triggerEvent: payload,
        logs: []
      }
    });

    const logs: any[] = [];

    try {
      for (const step of workflow.steps) {
        let stepResult: any = { stepId: step.id, type: step.type, status: "SUCCESS" };
        
        try {
          if (step.type === "ACTION") {
            stepResult = await this.executeAction(step, payload);
          } else if (step.type === "CONDITION") {
            stepResult = await this.executeCondition(step, payload);
            if (!stepResult.passed) {
              logs.push({ ...stepResult, status: "HALTED" });
              break; // Stop execution
            }
          } else if (step.type === "DELAY") {
            // For a robust system, DELAY pauses execution and schedules a retry in a Task Queue.
            // For this implementation, we will log it as skipped unless we implement a robust queue.
            stepResult = { stepId: step.id, status: "SKIPPED", reason: "Delay requires background job queue." };
          }
          logs.push(stepResult);
        } catch (e: any) {
          logs.push({ stepId: step.id, status: "FAILED", error: e.message });
          throw e; // Abort further steps
        }
      }

      await db.workflowExecution.update({
        where: { id: execution.id },
        data: { status: "COMPLETED", completedAt: new Date(), logs: logs }
      });
    } catch (error) {
      await db.workflowExecution.update({
        where: { id: execution.id },
        data: { status: "FAILED", completedAt: new Date(), logs: logs }
      });
    }
  }

  private static async executeAction(step: any, payload: any) {
    const config = (step.config as any) || {};
    
    switch (step.actionType) {
      case "CREATE_TASK":
        if (!payload.campaignId) throw new Error("Missing campaignId for CREATE_TASK");
        
        // Find a super admin to act as author if none provided
        let authorId = config.authorId || payload.userId;
        if (!authorId) {
          const admin = await db.user.findFirst({ where: { role: "SUPER_ADMIN" }});
          authorId = admin?.id;
        }

        if (!authorId) throw new Error("No author available for automated task.");

        await db.task.create({
          data: {
            title: config.title || "Automated Task",
            description: config.description || "Generated by workflow",
            campaignId: payload.campaignId,
            authorId: authorId,
            priority: "MEDIUM",
            status: "TODO"
          }
        });
        break;

      case "NOTIFY_TEAM":
        if (payload.campaignId) {
          const campaign = await db.campaign.findUnique({
            where: { id: payload.campaignId },
            include: { teamMembers: true }
          });
          if (campaign) {
            const userIds = campaign.teamMembers.map((tm: any) => tm.userId);
            if (userIds.length > 0) {
              await NotificationService.notifyUsers(userIds, {
                type: "SYSTEM_ALERT",
                title: config.title || "Workflow Alert",
                message: config.message || "An automated workflow triggered this alert.",
                priority: "MEDIUM"
              });
            }
          }
        }
        break;

      case "NOTIFY_MANAGER":
        if (payload.campaignId) {
          const campaign = await db.campaign.findUnique({
            where: { id: payload.campaignId },
            include: { teamMembers: { where: { role: "MANAGER" }, include: { user: true } } }
          });
          if (campaign && campaign.teamMembers.length > 0) {
            const managerIds = campaign.teamMembers.map((tm: any) => tm.userId);
            await NotificationService.notifyUsers(managerIds, {
              type: "SYSTEM_ALERT",
              title: config.title || "Task Completed",
              message: config.message || `Task was completed in campaign: ${campaign.name}`,
              priority: "HIGH"
            });
          }
        }
        break;

      case "CLOSE_REMAINING_TASKS":
        if (payload.campaignId) {
          await db.task.updateMany({
            where: { 
              campaignId: payload.campaignId,
              status: { not: "DONE" }
            },
            data: { status: "DONE" }
          });
          console.log(`[WorkflowEngine] Closed remaining tasks for campaign ${payload.campaignId}`);
        }
        break;

      case "DASHBOARD_ALERT":
        // For tasks (like Overdue / Due Tomorrow)
        if (payload.assigneeId) {
          await NotificationService.createNotification({
            userId: payload.assigneeId,
            type: "TASK_ASSIGNED", // High priority dashboard alert
            title: config.title || "Dashboard Alert",
            message: config.message || `Alert for task: ${payload.title}`,
            entityId: payload.taskId,
            entityType: "TASK",
            priority: "CRITICAL",
            link: `/tasks`
          });
        }
        break;

      case "SEND_EMAIL":
      case "SEND_WHATSAPP":
        if (payload.assigneeId || payload.userId) {
            const userId = payload.assigneeId || payload.userId;
            await NotificationService.createNotification({
                userId: userId,
                type: "SYSTEM_ALERT", // Uses NotificationService to determine channels
                title: config.title || "System Message",
                message: config.message || "Automated email/whatsapp message"
            });
        }
        break;

      case "GENERATE_AI_SUMMARY":
        // Generates an AI summary for the campaign
        if (payload.campaignId) {
            // Implementation delegates to AI service
            console.log("[WorkflowEngine] GENERATE_AI_SUMMARY mocked for campaign", payload.campaignId);
        }
        break;
      
      case "GENERATE_CALENDAR_EVENTS":
        if (payload.campaignId) {
          await db.event.create({
            data: {
              title: config.title || "Automated Campaign Event",
              type: "CAMPAIGN_LAUNCH",
              start: new Date(),
              campaignId: payload.campaignId,
              allDay: true
            }
          });
        }
        break;

      default:
        console.warn(`Unknown action type: ${step.actionType}`);
    }

    return { stepId: step.id, type: "ACTION", actionType: step.actionType, status: "SUCCESS" };
  }

  private static async executeCondition(step: any, payload: any) {
    const config = (step.config as any) || {};
    let passed = true;
    
    if (config.field && config.value !== undefined) {
      const actualValue = payload[config.field];
      if (config.operator === "equals" && actualValue !== config.value) passed = false;
      if (config.operator === "not_equals" && actualValue === config.value) passed = false;
      if (config.operator === "gt" && actualValue <= config.value) passed = false;
    }
    
    return { stepId: step.id, type: "CONDITION", passed };
  }
}
